DB_TABLE_IDENTIFIED_ADDRESS = 'identifiedAddress'
DB_TABLE_PENDING_ADDRESS = 'pendingAddress'
DB_TABLE_SCORE = 'score'
DB_TABLE_USER = 'user'
DB_USER_ID = 'userId'
DB_CHAIN = 'chain'
DB_ETH_ADDRESS = 'ethAddress'
DB_ADDRESS = 'address'
DB_TIMESTAMP = 'timestamp'
DB_SCORE = 'score'
DB_STAKE = 'stake'
DB_VERIFIER_ID = 'verifierId'
DB_DESCRIPTION = 'description'
DB_LINK = 'link'
DB_TWITTER = 'twitter'
DB_SUBMITTED_AT = 'submittedAt'

SCORE_ENGINE_HTTP_SERVER_PORT = 3001

ETHERSCAN_KOVAN_BASEPOINT = 'https://api-kovan.etherscan.io/'
